export const DAYS = {
  brust: {
    id: "brust",
    label: "Brust",
    icon: "dumbbell",
    tag: "Push · Mo",
    duration: "60–75 Min",
    accent: "#6366f1",
    accentDim: "#1e1b35",
    bg: "#0c0a14",
    headerBg: "linear-gradient(135deg, #1a1528 0%, #0f0d1a 100%)",
    exercises: [
      { id: "b1", name: "Schrägbank Langhantel", sub: "Incline Barbell Press", focus: "Obere Brust", focusColor: "#6366f1", sets: 5, reps: "6–8", weight: "28–30 kg", rest: 180, tip: "30–45° Neigung. Schulterblätter zusammenziehen, Ellbogen leicht nach innen. Deine Priorität — hier die meiste Energie rein.", primary: true },
      { id: "b2", name: "Flachbank Langhantel", sub: "Flat Barbell Bench Press", focus: "Mittlere Brust", focusColor: "#8b5cf6", sets: 3, reps: "8–10", weight: "32–35 kg", rest: 150, tip: "Klassische Compound. Fußkontakt zum Boden, Rücken leicht gebogen, Stange zur unteren Brust.", primary: true },
      { id: "b3", name: "Schrägbank Kurzhantel", sub: "Incline Dumbbell Press", focus: "Obere Brust", focusColor: "#6366f1", sets: 4, reps: "10–12", weight: "12 kg / Hand", rest: 120, tip: "Bessere Range of Motion als Langhantel. Hände neutral oder supiniert für mehr Dehnung.", primary: false },
      { id: "b4", name: "Kurzhantel Flyes", sub: "Dumbbell Flyes", focus: "Innen / Dehnung", focusColor: "#a78bfa", sets: 3, reps: "12–15", weight: "10–12 kg / Hand", rest: 90, tip: "Flachbank. Arme leicht gebeugt, großer Bogen nach unten — maximale Dehnung.", primary: false },
      { id: "b5", name: "Maschine Chest Press", sub: "Machine Chest Press", focus: "Untere Brust", focusColor: "#7c3aed", sets: 3, reps: "10–12", weight: "20–30 kg*", rest: 120, tip: "Gewicht erste Session einpendeln. Sitz auf Brusthöhe einstellen. Kontraktion halten, langsam zurück.", primary: false },
      { id: "b6", name: "Pec Deck / Butterfly", sub: "Machine Fly", focus: "Isolation / Pump", focusColor: "#c4b5fd", sets: 3, reps: "15–20", weight: "35–40 kg", rest: 60, tip: "Finisher. Fokus auf Muskelmind-Connection, langsam und kontrolliert.", primary: false },
    ],
    notes: [
      "Aufwärmen: 10 Min leichtes Cardio + 2 Warmup-Sets vor Compound",
      "Progressive Overload: Jede Woche +1 Rep oder +2,5 kg anstreben",
      "Protein-Timing: 30–40g Protein innerhalb 90 Min nach Training",
      "Trizeps werden bei Pressing mittrainiert — kein separater Fokus nötig",
    ],
  },
  ruecken: {
    id: "ruecken",
    label: "Rücken",
    icon: "back",
    tag: "Pull · Mi",
    duration: "60–70 Min",
    accent: "#0ea5e9",
    accentDim: "#0c1e30",
    bg: "#080c12",
    headerBg: "linear-gradient(135deg, #0d1a2a 0%, #080c12 100%)",
    exercises: [
      { id: "r1", name: "Rudern Maschine", sub: "Seated Row Machine", focus: "Mittlerer Rücken", focusColor: "#0ea5e9", sets: 4, reps: "8–10", weight: "50–70 kg*", rest: 150, tip: "Wichtigste Übung für Haltung. Schulterblätter am Ende zusammenquetschen und 1 Sek halten.", primary: true, posture: true },
      { id: "r2", name: "Latziehen zur Brust", sub: "Lat Pulldown", focus: "Latissimus", focusColor: "#6366f1", sets: 4, reps: "10–12", weight: "50–60 kg*", rest: 120, tip: "Stange zur oberen Brust ziehen, nicht hinter den Kopf. Ellbogen nach unten-hinten führen.", primary: true, posture: false },
      { id: "r3", name: "Face Pulls", sub: "Cable Face Pull", focus: "Hintere Schulter", focusColor: "#10b981", sets: 4, reps: "15–20", weight: "15–25 kg", rest: 90, tip: "Kabelzug auf Augenhöhe. Seil zu den Ohren ziehen, Ellbogen hoch. Direkte Haltungskorrektur.", primary: false, posture: true },
      { id: "r4", name: "Kurzhantel Rudern", sub: "Single Arm Dumbbell Row", focus: "Oberer Rücken", focusColor: "#8b5cf6", sets: 3, reps: "10–12", weight: "20–30 kg / Hand", rest: 90, tip: "Knie auf Bank, Rücken gerade. Hantel gerade nach oben ziehen. Pro Seite.", primary: false, posture: false },
      { id: "r5", name: "Reverse Flyes Maschine", sub: "Pec Deck Reverse", focus: "Hintere Schulter", focusColor: "#10b981", sets: 3, reps: "15–20", weight: "20–35 kg", rest: 60, tip: "Pec Deck umgekehrt. Arme nach hinten-außen. Direkt gegen Rundrücken.", primary: false, posture: true },
      { id: "r6", name: "Hyperextensions", sub: "Back Extension", focus: "Unterer Rücken", focusColor: "#10b981", sets: 3, reps: "12–15", weight: "Körpergewicht", rest: 60, tip: "Langsam und kontrolliert. Nicht überstrecken. Bei 140 kg besonders wichtig.", primary: false, posture: true },
    ],
    notes: [
      "Brust dehnen nach dem Training: Arm in Türrahmen, 30 Sek pro Seite",
      "Face Pulls nie zu schwer — Technik wichtiger als Gewicht",
      "Rundrücken verbessert sich in 6–8 Wochen bei konsequentem Training",
      "Progression: Sobald 12 saubere Reps → +5 kg",
    ],
  },
  beine: {
    id: "beine",
    label: "Beine",
    icon: "legs",
    tag: "Legs · Fr",
    duration: "55–65 Min",
    accent: "#f59e0b",
    accentDim: "#2a1f0a",
    bg: "#0e0a00",
    headerBg: "linear-gradient(135deg, #1a1400 0%, #0e0a00 100%)",
    exercises: [
      { id: "l1", name: "Beinpresse", sub: "Leg Press Machine", focus: "Quadrizeps / Po", focusColor: "#f59e0b", sets: 4, reps: "10–12", weight: "80–120 kg*", rest: 150, tip: "Füße schulterbreit, mittig auf der Platte. Knie nicht ganz durchstrecken. Rückenschonendste Alternative zu Kniebeugen.", primary: true },
      { id: "l2", name: "Beinstrecker", sub: "Leg Extension", focus: "Quadrizeps", focusColor: "#fbbf24", sets: 3, reps: "12–15", weight: "40–60 kg*", rest: 90, tip: "Oben kurz halten, langsam runter. Isolation für den vorderen Oberschenkel.", primary: false },
      { id: "l3", name: "Bein-Curl liegend", sub: "Lying Leg Curl", focus: "Beinbeuger", focusColor: "#d97706", sets: 3, reps: "12–15", weight: "30–50 kg*", rest: 90, tip: "Hüfte auf der Bank halten. Langsam strecken — Beinbeuger sind oft vernachlässigt.", primary: false },
      { id: "l4", name: "Wadenheben Maschine", sub: "Calf Raise Machine", focus: "Waden", focusColor: "#92400e", sets: 4, reps: "15–20", weight: "60–80 kg*", rest: 60, tip: "Volle Bewegung — ganz runter, ganz rauf. Oben 1 Sek halten.", primary: false },
      { id: "l5", name: "Hip Thrust Maschine", sub: "Hip Thrust Machine", focus: "Po / Hüfte", focusColor: "#f59e0b", sets: 3, reps: "12–15", weight: "40–70 kg*", rest: 90, tip: "Stärkt den Po der bei Schreibtischarbeit einschläft. Oben Gesäß anspannen und 1 Sek halten.", primary: false },
      { id: "l6", name: "Abduktor Maschine", sub: "Hip Abductor", focus: "Hüfte / Stabilität", focusColor: "#b45309", sets: 3, reps: "15–20", weight: "40–60 kg*", rest: 60, tip: "Stabilisiert die Hüfte — besonders wichtig bei höherem Körpergewicht.", primary: false },
    ],
    notes: [
      "Kniebeugen bewusst weggelassen — Beinpresse ist rückenschonender",
      "Waden täglich dehnen — verkürzte Waden belasten Knie und Rücken",
      "Po-Training ist kein Luxus — schwacher Po = schlechte Haltung",
      "Progression: +5–10 kg sobald 15 Reps sauber möglich",
    ],
  },
  kettlebell: {
    id: "kettlebell",
    label: "Kettlebell",
    icon: "kettlebell",
    tag: "Kraft · Kettlebell",
    duration: "35–45 Min",
    accent: "#10b981",
    accentDim: "#0a2019",
    bg: "#07120e",
    headerBg: "linear-gradient(135deg, #0d1f18 0%, #07120e 100%)",
    exercises: [
      { id: "k1", name: "Kettlebell Swing", sub: "Two-Hand Swing", focus: "Hüfte / Rücken", focusColor: "#10b981", sets: 4, reps: "10–12", weight: "20–24 kg", rest: 90, tip: "Kraft aus der Hüfte, nicht aus den Armen. Rücken gerade — top für die hintere Kette und Haltung.", primary: true, posture: true },
      { id: "k2", name: "Goblet Squat", sub: "Kettlebell Goblet Squat", focus: "Beine / Rumpf", focusColor: "#34d399", sets: 4, reps: "8–10", weight: "20–24 kg", rest: 120, tip: "Kettlebell vor der Brust halten, aufrechter Oberkörper. Tief gehen, Fersen am Boden.", primary: true, posture: false },
      { id: "k3", name: "Clean & Press", sub: "Kettlebell Clean and Press", focus: "Ganzkörper / Schulter", focusColor: "#10b981", sets: 3, reps: "6–8 / Seite", weight: "16–20 kg", rest: 120, tip: "Sauberer Clean in Front-Rack, dann kontrolliert überkopf drücken. Pro Seite.", primary: true, posture: false },
      { id: "k4", name: "Einarmiges Rudern", sub: "Single-Arm KB Row", focus: "Oberer Rücken", focusColor: "#059669", sets: 3, reps: "10–12 / Seite", weight: "20–24 kg", rest: 90, tip: "Abgestützt, Rücken gerade. Ellbogen nach hinten, Schulterblatt zusammenziehen.", primary: false, posture: true },
      { id: "k5", name: "Kettlebell Deadlift", sub: "KB Romanian Deadlift", focus: "Beinbeuger / Po", focusColor: "#34d399", sets: 3, reps: "10–12", weight: "24–28 kg", rest: 90, tip: "Hüfte nach hinten schieben, leichte Kniebeugung. Dehnung in den Beinbeugern spüren.", primary: false, posture: true },
      { id: "k6", name: "Farmer's Carry", sub: "Kettlebell Carry", focus: "Griff / Rumpf", focusColor: "#065f46", sets: 3, reps: "30–40 m", weight: "2×20 kg", rest: 60, tip: "Aufrecht gehen, Schultern hinten, Rumpf fest. Stärkt Griff und Rumpfstabilität.", primary: false, posture: true },
    ],
    notes: [
      "Mittlere Intensität — Fokus auf saubere Technik und Kraft, nicht auf Masse",
      "Swings sind der Star: hüftdominant, rückenfreundlich, ideal bei Schreibtischhaltung",
      "Progression: nächstschwerere Kettlebell erst wenn alle Sätze sauber sitzen",
      "Gut als kürzerer Tag zwischen den schweren Einheiten",
    ],
  },
};
