export const DAYS = {
  brust: {
    id: "brust",
    label: "Brust",
    icon: "dumbbell",
    tag: "Push · Mo",
    duration: "60–75 Min",
    accent: "#6366f1",
    accentDim: "#1e1b35",
    bg: "#0c0a14",
    headerBg: "linear-gradient(135deg, #1a1528 0%, #0f0d1a 100%)",
    exercises: [
      { id: "b1", name: "Schrägbank Langhantel", sub: "Incline Barbell Press", focus: "Obere Brust", focusColor: "#6366f1", sets: 4, reps: "6–8", weight: "28–30 kg", rest: 180, tip: "30–45° Neigung. Schulterblätter zusammenziehen, Ellbogen leicht nach innen. Deine Priorität — aber halte 1–2 Wiederholungen in Reserve, damit noch Kraft für die Folgeübungen bleibt.", primary: true },
      { id: "b2", name: "Flachbank Langhantel", sub: "Flat Barbell Bench Press", focus: "Mittlere Brust", focusColor: "#8b5cf6", sets: 3, reps: "8–10", weight: "32–35 kg", rest: 150, tip: "Klassische Compound. Fußkontakt zum Boden, Rücken leicht gebogen, Stange zur unteren Brust.", primary: true },
      { id: "b3", name: "Schrägbank Kurzhantel", sub: "Incline Dumbbell Press", focus: "Obere Brust", focusColor: "#6366f1", sets: 4, reps: "10–12", weight: "12 kg / Hand", rest: 120, tip: "Bessere Range of Motion als Langhantel. Hände neutral oder supiniert für mehr Dehnung.", primary: false },
      { id: "b4", name: "Kurzhantel Flyes", sub: "Dumbbell Flyes", focus: "Innen / Dehnung", focusColor: "#a78bfa", sets: 3, reps: "12–15", weight: "10–12 kg / Hand", rest: 90, tip: "Flachbank. Arme leicht gebeugt, großer Bogen nach unten — maximale Dehnung.", primary: false },
      { id: "b5", name: "Maschine Chest Press", sub: "Machine Chest Press", focus: "Untere Brust", focusColor: "#7c3aed", sets: 3, reps: "10–12", weight: "20–30 kg*", rest: 120, tip: "Gewicht erste Session einpendeln. Sitz auf Brusthöhe einstellen. Kontraktion halten, langsam zurück.", primary: false },
      { id: "b6", name: "Pec Deck / Butterfly", sub: "Machine Fly", focus: "Isolation / Pump", focusColor: "#c4b5fd", sets: 3, reps: "15–20", weight: "35–40 kg", rest: 60, tip: "Finisher. Fokus auf Muskelmind-Connection, langsam und kontrolliert.", primary: false },
    ],
    notes: [
      "Aufwärmen: 10 Min leichtes Cardio + 2 Warmup-Sets vor Compound",
      "Schrägbank auf 4 Sätze reduziert — nicht bis zum Muskelversagen, 1–2 Wdh in Reserve lassen, sonst fehlt die Kraft für den Rest",
      "Progressive Overload: Jede Woche +1 Rep oder +2,5 kg anstreben",
      "Protein-Timing: 30–40g Protein innerhalb 90 Min nach Training",
      "Trizeps werden bei Pressing mittrainiert — kein separater Fokus nötig",
    ],
    stretches: [
      { id: "bs1", name: "Türrahmen-Brustdehnung", sub: "Doorway Pec Stretch", target: "Brust", hold: 30, tip: "Unterarm an den Türrahmen, Ellbogen auf Schulterhöhe, sanft nach vorne lehnen. Pro Seite 30s." },
      { id: "bs2", name: "Cross-Body Schulter", sub: "Cross-Body Shoulder", target: "Hintere Schulter", hold: 30, tip: "Arm gerade vor die Brust ziehen, mit dem anderen Arm sanft heranziehen. Pro Seite." },
      { id: "bs3", name: "Trizeps Overhead", sub: "Overhead Triceps", target: "Trizeps", hold: 30, tip: "Ellbogen hinter den Kopf, Hand Richtung gegenüberliegendes Schulterblatt. Pro Seite." },
      { id: "bs4", name: "Brustöffner an der Wand", sub: "Wall Chest Opener", target: "Brust / Schulter", hold: 30, tip: "Hand an die Wand, Körper langsam wegdrehen bis die Brust dehnt." },
      { id: "bs5", name: "Figure-4 / Taube", sub: "Piriformis Stretch", target: "Po / Hüfte", hold: 30, tip: "Knöchel über das gegenüberliegende Knie, sanft heranziehen. Gegen tight Glutes vom Sitzen. Pro Seite." },
      { id: "bs6", name: "Hüftbeuger-Ausfallschritt", sub: "Hip Flexor Lunge", target: "Hüftbeuger", hold: 30, tip: "Tiefer Ausfallschritt, Becken nach vorne schieben. Öffnet die vom Sitzen verkürzte Hüfte. Pro Seite." },
    ],
  },
  ruecken: {
    id: "ruecken",
    label: "Rücken",
    icon: "back",
    tag: "Pull · Mi",
    duration: "60–70 Min",
    accent: "#0ea5e9",
    accentDim: "#0c1e30",
    bg: "#080c12",
    headerBg: "linear-gradient(135deg, #0d1a2a 0%, #080c12 100%)",
    exercises: [
      { id: "r1", name: "Rudern Maschine", sub: "Seated Row Machine", focus: "Mittlerer Rücken", focusColor: "#0ea5e9", sets: 4, reps: "8–10", weight: "50–70 kg*", rest: 150, tip: "Wichtigste Übung für Haltung. Schulterblätter am Ende zusammenquetschen und 1 Sek halten.", primary: true, posture: true },
      { id: "r2", name: "Latziehen zur Brust", sub: "Lat Pulldown", focus: "Latissimus", focusColor: "#6366f1", sets: 4, reps: "10–12", weight: "50–60 kg*", rest: 120, tip: "Stange zur oberen Brust ziehen, nicht hinter den Kopf. Ellbogen nach unten-hinten führen.", primary: true, posture: false },
      { id: "r3", name: "Face Pulls", sub: "Cable Face Pull", focus: "Hintere Schulter", focusColor: "#10b981", sets: 4, reps: "15–20", weight: "15–25 kg", rest: 90, tip: "Kabelzug auf Augenhöhe. Seil zu den Ohren ziehen, Ellbogen hoch. Direkte Haltungskorrektur.", primary: false, posture: true },
      { id: "r4", name: "Kurzhantel Rudern", sub: "Single Arm Dumbbell Row", focus: "Oberer Rücken", focusColor: "#8b5cf6", sets: 3, reps: "10–12", weight: "20–30 kg / Hand", rest: 90, tip: "Knie auf Bank, Rücken gerade. Hantel gerade nach oben ziehen. Pro Seite.", primary: false, posture: false },
      { id: "r5", name: "Reverse Flyes Maschine", sub: "Pec Deck Reverse", focus: "Hintere Schulter", focusColor: "#10b981", sets: 3, reps: "15–20", weight: "20–35 kg", rest: 60, tip: "Pec Deck umgekehrt. Arme nach hinten-außen. Direkt gegen Rundrücken.", primary: false, posture: true },
      { id: "r6", name: "Hyperextensions", sub: "Back Extension", focus: "Unterer Rücken", focusColor: "#10b981", sets: 3, reps: "12–15", weight: "Körpergewicht", rest: 60, tip: "Langsam und kontrolliert. Nicht überstrecken. Bei 140 kg besonders wichtig.", primary: false, posture: true },
    ],
    notes: [
      "Brust dehnen nach dem Training: Arm in Türrahmen, 30 Sek pro Seite",
      "Face Pulls nie zu schwer — Technik wichtiger als Gewicht",
      "Rundrücken verbessert sich in 6–8 Wochen bei konsequentem Training",
      "Progression: Sobald 12 saubere Reps → +5 kg",
    ],
    stretches: [
      { id: "rs1", name: "Lat-Dehnung", sub: "Overhead Lat Stretch", target: "Latissimus", hold: 30, tip: "An Stange/Türrahmen fassen, Hüfte nach hinten schieben, Lat lang machen. Pro Seite." },
      { id: "rs2", name: "Katze-Kuh", sub: "Cat-Cow", target: "BWS-Mobilität", hold: 60, tip: "Im Vierfüßlerstand Rücken abwechselnd runden und strecken, ruhig atmen." },
      { id: "rs3", name: "Kindhaltung", sub: "Child's Pose", target: "Unterer Rücken", hold: 45, tip: "Fersensitz, Arme lang nach vorne, Stirn Richtung Boden, tief atmen." },
      { id: "rs4", name: "Brustöffner", sub: "Chest Opener", target: "Anti-Rundrücken", hold: 30, tip: "Hände hinter dem Rücken verschränken, Brust öffnen — direkt gegen Rundrücken." },
      { id: "rs5", name: "Nackendehnung", sub: "Neck Stretch", target: "Nacken", hold: 30, tip: "Kopf sanft zur Seite neigen, Schulter unten lassen. Pro Seite." },
      { id: "rs6", name: "Figure-4 / Taube", sub: "Piriformis Stretch", target: "Po / Hüfte", hold: 30, tip: "Knöchel über das gegenüberliegende Knie, sanft heranziehen. Gegen tight Glutes vom Sitzen. Pro Seite." },
      { id: "rs7", name: "Hüftbeuger-Ausfallschritt", sub: "Hip Flexor Lunge", target: "Hüftbeuger", hold: 30, tip: "Tiefer Ausfallschritt, Becken nach vorne schieben. Öffnet die vom Sitzen verkürzte Hüfte. Pro Seite." },
    ],
  },
  beine: {
    id: "beine",
    label: "Beine",
    icon: "legs",
    tag: "Legs · Fr",
    duration: "55–65 Min",
    accent: "#f59e0b",
    accentDim: "#2a1f0a",
    bg: "#0e0a00",
    headerBg: "linear-gradient(135deg, #1a1400 0%, #0e0a00 100%)",
    exercises: [
      { id: "l1", name: "Beinpresse", sub: "Leg Press Machine", focus: "Quadrizeps / Po", focusColor: "#f59e0b", sets: 4, reps: "10–12", weight: "80–120 kg*", rest: 150, tip: "Füße schulterbreit, mittig auf der Platte. Knie nicht ganz durchstrecken. Rückenschonendste Alternative zu Kniebeugen.", primary: true },
      { id: "l2", name: "Beinstrecker", sub: "Leg Extension", focus: "Quadrizeps", focusColor: "#fbbf24", sets: 3, reps: "12–15", weight: "40–60 kg*", rest: 90, tip: "Oben kurz halten, langsam runter. Isolation für den vorderen Oberschenkel.", primary: false },
      { id: "l3", name: "Beinbeuger sitzend", sub: "Seated Leg Curl", focus: "Beinbeuger", focusColor: "#d97706", sets: 3, reps: "12–15", weight: "30–50 kg*", rest: 90, tip: "Aufrecht sitzen, Polster auf die Waden/Unterschenkel, Beine kontrolliert beugen und langsam strecken. Bequem auch mit Bauch — keine Bauchlage nötig.", primary: false },
      { id: "l4", name: "Wadenheben Maschine", sub: "Calf Raise Machine", focus: "Waden", focusColor: "#92400e", sets: 4, reps: "15–20", weight: "60–80 kg*", rest: 60, tip: "Volle Bewegung — ganz runter, ganz rauf. Oben 1 Sek halten.", primary: false },
      { id: "l5", name: "Hip Thrust Maschine", sub: "Hip Thrust Machine", focus: "Po / Hüfte", focusColor: "#f59e0b", sets: 3, reps: "12–15", weight: "40–70 kg*", rest: 90, tip: "Stärkt den Po der bei Schreibtischarbeit einschläft. Oben Gesäß anspannen und 1 Sek halten.", primary: false },
      { id: "l6", name: "Abduktor Maschine", sub: "Hip Abductor", focus: "Hüfte / Stabilität", focusColor: "#b45309", sets: 3, reps: "15–20", weight: "40–60 kg*", rest: 60, tip: "Stabilisiert die Hüfte — besonders wichtig bei höherem Körpergewicht.", primary: false },
      { id: "l7", name: "Adduktoren Maschine", sub: "Hip Adductor (Inner Thigh)", focus: "Adduktoren / Innenschenkel", focusColor: "#d97706", sets: 3, reps: "15–20", weight: "40–60 kg*", rest: 60, tip: "Sitzend, Polster innen an den Knien, Beine gegen den Widerstand zusammenführen, kurz halten, langsam kontrolliert öffnen. Direkt für die Problemzone Innenschenkel.", primary: false },
    ],
    notes: [
      "Kniebeugen bewusst weggelassen — Beinpresse ist rückenschonender",
      "Waden täglich dehnen — verkürzte Waden belasten Knie und Rücken",
      "Po-Training ist kein Luxus — schwacher Po = schlechte Haltung",
      "Progression: +5–10 kg sobald 15 Reps sauber möglich",
    ],
    stretches: [
      { id: "ls1", name: "Quadrizeps stehend", sub: "Standing Quad Stretch", target: "Quadrizeps", hold: 30, tip: "Fuß zum Po ziehen, Knie zusammen, Hüfte leicht nach vorne. Pro Seite." },
      { id: "ls2", name: "Beinbeuger-Dehnung", sub: "Hamstring Stretch", target: "Beinbeuger", hold: 30, tip: "Bein gestreckt vor dir, Hüfte nach hinten, Rücken gerade. Pro Seite." },
      { id: "ls3", name: "Wadendehnung an der Wand", sub: "Wall Calf Stretch", target: "Waden", hold: 30, tip: "Ferse am Boden, hinteres Bein gestreckt, gegen die Wand lehnen. Pro Seite." },
      { id: "ls4", name: "Hüftbeuger-Ausfallschritt", sub: "Hip Flexor Lunge", target: "Hüftbeuger", hold: 30, tip: "Tiefer Ausfallschritt, Becken nach vorne schieben — wichtig bei viel Sitzen. Pro Seite." },
      { id: "ls5", name: "Figure-4 / Taube", sub: "Piriformis Stretch", target: "Po / Hüfte", hold: 30, tip: "Knöchel über das gegenüberliegende Knie, sanft heranziehen. Pro Seite." },
    ],
    warmup: [
      { id: "lw1", name: "Glute Bridge", sub: "Glute Bridge", target: "Gesäß", reps: "2×15", tip: "Auf dem Rücken, Fersen nah am Po. Becken hochdrücken, oben Gesäß 1 Sek fest anspannen — aktiviert die vom Sitzen eingeschlafenen Glutes." },
      { id: "lw2", name: "Clamshells", sub: "Clamshell", target: "Gesäß (seitlich)", reps: "2×15/Seite", tip: "Seitlage, Knie gebeugt. Oberes Knie öffnen, ohne das Becken nach hinten zu drehen." },
      { id: "lw3", name: "Monster Walks", sub: "Banded Lateral Walk", target: "Abduktoren / Gesäß", reps: "2×10 Schritte", tip: "Band um die Knie, leichte Hocke, seitlich gehen und Bandspannung halten." },
    ],
  },
  kettlebell: {
    id: "kettlebell",
    label: "Kettlebell",
    icon: "kettlebell",
    tag: "Kraft · Kettlebell",
    duration: "35–45 Min",
    accent: "#10b981",
    accentDim: "#0a2019",
    bg: "#07120e",
    headerBg: "linear-gradient(135deg, #0d1f18 0%, #07120e 100%)",
    exercises: [
      { id: "k1", name: "Kettlebell Swing", sub: "Two-Hand Swing", focus: "Hüfte / Rücken", focusColor: "#10b981", sets: 4, reps: "10–12", weight: "20–24 kg", rest: 90, tip: "Kraft aus der Hüfte, nicht aus den Armen. Rücken gerade — top für die hintere Kette und Haltung.", primary: true, posture: true },
      { id: "k2", name: "Goblet Squat", sub: "Kettlebell Goblet Squat", focus: "Beine / Rumpf", focusColor: "#34d399", sets: 4, reps: "8–10", weight: "20–24 kg", rest: 120, tip: "Kettlebell vor der Brust halten, aufrechter Oberkörper. Tief gehen, Fersen am Boden.", primary: true, posture: false },
      { id: "k3", name: "Clean & Press", sub: "Kettlebell Clean and Press", focus: "Ganzkörper / Schulter", focusColor: "#10b981", sets: 3, reps: "6–8 / Seite", weight: "16–20 kg", rest: 120, tip: "Sauberer Clean in Front-Rack, dann kontrolliert überkopf drücken. Pro Seite.", primary: true, posture: false },
      { id: "k4", name: "Einarmiges Rudern", sub: "Single-Arm KB Row", focus: "Oberer Rücken", focusColor: "#059669", sets: 3, reps: "10–12 / Seite", weight: "20–24 kg", rest: 90, tip: "Abgestützt, Rücken gerade. Ellbogen nach hinten, Schulterblatt zusammenziehen.", primary: false, posture: true },
      { id: "k5", name: "Kettlebell Deadlift", sub: "KB Romanian Deadlift", focus: "Beinbeuger / Po", focusColor: "#34d399", sets: 3, reps: "10–12", weight: "24–28 kg", rest: 90, tip: "Hüfte nach hinten schieben, leichte Kniebeugung. Dehnung in den Beinbeugern spüren.", primary: false, posture: true },
      { id: "k6", name: "Farmer's Carry", sub: "Kettlebell Carry", focus: "Griff / Rumpf", focusColor: "#065f46", sets: 3, reps: "30–40 m", weight: "2×20 kg", rest: 60, tip: "Aufrecht gehen, Schultern hinten, Rumpf fest. Stärkt Griff und Rumpfstabilität.", primary: false, posture: true },
    ],
    notes: [
      "Mittlere Intensität — Fokus auf saubere Technik und Kraft, nicht auf Masse",
      "Swings sind der Star: hüftdominant, rückenfreundlich, ideal bei Schreibtischhaltung",
      "Progression: nächstschwerere Kettlebell erst wenn alle Sätze sauber sitzen",
      "Gut als kürzerer Tag zwischen den schweren Einheiten",
    ],
    stretches: [
      { id: "ks1", name: "Hüftbeuger-Ausfallschritt", sub: "Hip Flexor Lunge", target: "Hüfte", hold: 30, tip: "Becken nach vorne schieben, aufrecht bleiben. Pro Seite." },
      { id: "ks2", name: "Beinbeuger-Dehnung", sub: "Hamstring Stretch", target: "Beinbeuger", hold: 30, tip: "Hüfte nach hinten, Rücken gerade. Pro Seite." },
      { id: "ks3", name: "Thoracic Rotation", sub: "Kneeling T-Spine Rotation", target: "BWS", hold: 30, tip: "Vierfüßlerstand, eine Hand hinter den Kopf, Ellbogen zur Decke drehen. Pro Seite." },
      { id: "ks4", name: "Schulterdehnung", sub: "Shoulder Stretch", target: "Schulter", hold: 30, tip: "Arm vor der Brust heranziehen. Pro Seite." },
      { id: "ks5", name: "Katze-Kuh", sub: "Cat-Cow", target: "Mobilität", hold: 60, tip: "Rücken abwechselnd runden und strecken, ruhig atmen." },
      { id: "ks6", name: "Figure-4 / Taube", sub: "Piriformis Stretch", target: "Po / Hüfte", hold: 30, tip: "Knöchel über das gegenüberliegende Knie, sanft heranziehen. Gegen tight Glutes vom Sitzen. Pro Seite." },
    ],
    warmup: [
      { id: "kw1", name: "Glute Bridge", sub: "Glute Bridge", target: "Gesäß", reps: "2×15", tip: "Becken hochdrücken, oben Gesäß fest anspannen. Aktiviert die Glutes vor dem Training." },
      { id: "kw2", name: "Bird-Dog", sub: "Bird Dog", target: "Rumpf / Gesäß", reps: "2×8/Seite", tip: "Vierfüßlerstand, gegenüberliegenden Arm und Bein strecken, Rumpf stabil halten." },
      { id: "kw3", name: "Monster Walks", sub: "Banded Lateral Walk", target: "Abduktoren / Gesäß", reps: "2×10 Schritte", tip: "Band um die Knie, leichte Hocke, seitlich gehen." },
    ],
  },
  fullbody: {
    id: "fullbody",
    label: "Full Body",
    icon: "fullbody",
    tag: "Ganzkörper · flexibel",
    duration: "75–100 Min",
    accent: "#a855f7",
    accentDim: "#1a1030",
    bg: "#0d0716",
    headerBg: "linear-gradient(135deg, #170b28 0%, #0d0716 100%)",
    exercises: [
      { id: "f1", name: "Bankdrücken", sub: "Barbell Bench Press", focus: "Brust", focusColor: "#a855f7", sets: 4, reps: "6–8", weight: "40–60 kg*", rest: 150, tip: "Schulterblätter zusammen, Füße fest, Stange zur unteren Brust. Der Haupt-Druck des Tages — hier die meiste Energie rein.", primary: true },
      { id: "f2", name: "Schrägbank Kurzhantel", sub: "Incline Dumbbell Press", focus: "Obere Brust", focusColor: "#c084fc", sets: 3, reps: "8–10", weight: "16–22 kg", rest: 120, tip: "30–45° Neigung, Kurzhanteln kontrolliert nach oben. Ergänzt das Bankdrücken für die obere Brust.", primary: false },
      { id: "f3", name: "Latzug", sub: "Lat Pulldown", focus: "Latissimus", focusColor: "#a855f7", sets: 3, reps: "8–10", weight: "45–65 kg*", rest: 120, tip: "Stange zur oberen Brust, Ellbogen nach unten-hinten, Schulterblätter senken. Vertikaler Zug.", primary: true },
      { id: "f4", name: "Rudern", sub: "Seated Cable Row", focus: "Oberer Rücken", focusColor: "#c084fc", sets: 3, reps: "10–12", weight: "45–60 kg*", rest: 90, tip: "Aufrecht sitzen, zum Bauch ziehen, Schulterblätter zusammen. Horizontaler Zug — wichtig für Rückendicke und Haltung.", primary: false, posture: true },
      { id: "f5", name: "Beinpresse", sub: "Leg Press", focus: "Quadrizeps / Po", focusColor: "#a855f7", sets: 3, reps: "10–12", weight: "80–120 kg*", rest: 150, tip: "Füße schulterbreit, mittig. Knie nicht ganz durchstrecken. Rückenschonende Bein-Grundübung.", primary: true },
      { id: "f6", name: "Beinbeuger sitzend", sub: "Seated Leg Curl", focus: "Beinbeuger", focusColor: "#c084fc", sets: 3, reps: "12–15", weight: "30–50 kg*", rest: 90, tip: "Aufrecht sitzen, Beine kontrolliert beugen und langsam strecken. Deckt die sonst fehlenden Hamstrings ab.", primary: false },
      { id: "f7", name: "Hip Thrust Maschine", sub: "Hip Thrust Machine", focus: "Po / Hüfte", focusColor: "#d8b4fe", sets: 3, reps: "12–15", weight: "40–70 kg*", rest: 90, tip: "Oben Gesäß fest anspannen und 1 Sek halten. Stärkt den vom Sitzen schwachen Po.", primary: false },
      { id: "f8", name: "Abduktor Maschine", sub: "Hip Abductor", focus: "Hüfte / Stabilität", focusColor: "#d8b4fe", sets: 3, reps: "15–20", weight: "40–60 kg*", rest: 60, tip: "Beine gegen den Widerstand nach außen. Stabilisiert die Hüfte.", primary: false },
      { id: "f9", name: "Adduktoren Maschine", sub: "Hip Adductor (Inner Thigh)", focus: "Adduktoren / Innenschenkel", focusColor: "#d8b4fe", sets: 3, reps: "15–20", weight: "40–60 kg*", rest: 60, tip: "Sitzend, Beine gegen den Widerstand zusammenführen, kurz halten, langsam öffnen. Für die Problemzone Innenschenkel.", primary: false },
      { id: "f10", name: "Wadenheben", sub: "Calf Raise", focus: "Waden", focusColor: "#d8b4fe", sets: 3, reps: "15–20", weight: "60–80 kg*", rest: 60, tip: "Volle Bewegung — ganz runter, ganz rauf. Oben 1 Sek halten.", primary: false },
      { id: "f11", name: "Poliquin Seitheben", sub: "Poliquin Lateral Raise", focus: "Seitliche Schulter", focusColor: "#c084fc", sets: 3, reps: "12–15", weight: "6–10 kg", rest: 60, tip: "Poliquin-Stil: leicht vorgebeugt, Daumen leicht nach unten, sauber heben und betont langsam senken. Kein Schwung.", primary: false },
      { id: "f12", name: "Face Pulls", sub: "Face Pull", focus: "Hintere Schulter / Haltung", focusColor: "#c084fc", sets: 3, reps: "15–20", weight: "20–35 kg*", rest: 60, tip: "Seil auf Gesichtshöhe, zu den Ohren ziehen, Schulterblätter zusammen. Top gegen Rundschultern.", primary: false, posture: true },
      { id: "f13", name: "Rope Pushdown", sub: "Rope Triceps Pushdown (Superset)", focus: "Trizeps", focusColor: "#c084fc", sets: 3, reps: "10–12", weight: "25–40 kg*", rest: 30, tip: "Am Kabel mit Seil (hohe Rolle): Seil runterdrücken, unten die Enden auseinander, Ellbogen fixiert. Superset — direkt zum Rope Curl.", primary: false },
      { id: "f14", name: "Rope Curl", sub: "Rope Cable Curl (Superset)", focus: "Bizeps", focusColor: "#c084fc", sets: 3, reps: "10–12", weight: "20–35 kg*", rest: 90, tip: "Gleiches Seil (tiefe Rolle): Seil nach oben curlen (Hammer-Grip), Ellbogen am Körper. Direkt nach dem Pushdown, danach Pause.", primary: false },
    ],
    notes: [
      "Ganzkörper-Tag für Wochen, in denen du seltener ins Gym kommst — triff alles auf einmal, inkl. Brust.",
      "Compounds zuerst (Bankdrücken, Latzug, Beinpresse), dann Isolationen.",
      "Trizeps + Bizeps im Superset (abwechselnd, kaum Pause) — spart Zeit am Ende.",
      "Zeit knapp? Isolationen zuerst weglassen (Abduktor/Adduktor/Waden/Seitheben), Compounds behalten.",
      "Bei 14 Übungen nicht überall bis zum Muskelversagen — 1–2 Wdh in Reserve lassen.",
    ],
    stretches: [
      { id: "fs1", name: "Türrahmen-Brustdehnung", sub: "Doorway Pec Stretch", target: "Brust", hold: 30, tip: "Unterarm an den Türrahmen, sanft nach vorne lehnen. Pro Seite." },
      { id: "fs2", name: "Lat-Dehnung", sub: "Overhead Lat Stretch", target: "Latissimus", hold: 30, tip: "An Stange fassen, Hüfte nach hinten, Lat lang machen. Pro Seite." },
      { id: "fs3", name: "Quadrizeps stehend", sub: "Standing Quad Stretch", target: "Quadrizeps", hold: 30, tip: "Fuß zum Po ziehen, Knie zusammen, Hüfte leicht nach vorne. Pro Seite." },
      { id: "fs4", name: "Beinbeuger-Dehnung", sub: "Hamstring Stretch", target: "Beinbeuger", hold: 30, tip: "Bein gestreckt, Hüfte nach hinten, Rücken gerade. Pro Seite." },
      { id: "fs5", name: "Hüftbeuger-Ausfallschritt", sub: "Hip Flexor Lunge", target: "Hüftbeuger", hold: 30, tip: "Tiefer Ausfallschritt, Becken nach vorne schieben. Pro Seite." },
      { id: "fs6", name: "Figure-4 / Taube", sub: "Piriformis Stretch", target: "Po / Hüfte", hold: 30, tip: "Knöchel über das gegenüberliegende Knie, sanft heranziehen. Pro Seite." },
    ],
    warmup: [
      { id: "fw1", name: "Katze-Kuh", sub: "Cat-Cow", target: "Mobilität", reps: "1×10", tip: "Im Vierfüßlerstand Rücken abwechselnd runden und strecken, ruhig atmen." },
      { id: "fw2", name: "Glute Bridge", sub: "Glute Bridge", target: "Gesäß", reps: "1×15", tip: "Becken hochdrücken, oben Gesäß anspannen — aktiviert den Po." },
      { id: "fw3", name: "Band Pull-Apart", sub: "Band Pull-Apart", target: "Schulter / Rücken", reps: "1×15", tip: "Band vor der Brust auseinanderziehen, Schulterblätter zusammen — wärmt Schultern und oberen Rücken auf." },
    ],
  },
  fullA: {
    id: "fullA",
    label: "Full Body A",
    icon: "fullbody",
    tag: "Ganzkörper · kurz A",
    duration: "45–60 Min",
    restHours: 48,
    accent: "#8b5cf6",
    accentDim: "#16122e",
    bg: "#0b0a1c",
    headerBg: "linear-gradient(135deg, #16122e 0%, #0b0a1c 100%)",
    exercises: [
      { id: "fa1", name: "Bankdrücken", sub: "Barbell Bench Press", focus: "Brust", focusColor: "#8b5cf6", sets: 4, reps: "6–8", weight: "40–60 kg*", rest: 150, tip: "Schulterblätter zusammen, Füße fest, Stange zur unteren Brust. Der Haupt-Druck der Session.", primary: true },
      { id: "fa2", name: "Latzug", sub: "Lat Pulldown", focus: "Latissimus", focusColor: "#a78bfa", sets: 3, reps: "8–10", weight: "45–65 kg*", rest: 120, tip: "Stange zur oberen Brust, Ellbogen nach unten-hinten, Schulterblätter senken.", primary: true },
      { id: "fa3", name: "Beinpresse", sub: "Leg Press", focus: "Quadrizeps / Po", focusColor: "#8b5cf6", sets: 3, reps: "10–12", weight: "80–120 kg*", rest: 150, tip: "Füße schulterbreit, mittig. Knie nicht ganz durchstrecken. Rückenschonende Bein-Grundübung.", primary: true },
      { id: "fa4", name: "Hip Thrust Maschine", sub: "Hip Thrust Machine", focus: "Po / Hüfte", focusColor: "#c4b5fd", sets: 3, reps: "12–15", weight: "40–70 kg*", rest: 90, tip: "Oben Gesäß fest anspannen und 1 Sek halten.", primary: false },
      { id: "fa5", name: "Poliquin Seitheben", sub: "Poliquin Lateral Raise", focus: "Seitliche Schulter", focusColor: "#a78bfa", sets: 3, reps: "12–15", weight: "6–10 kg", rest: 60, tip: "Leicht vorgebeugt, Daumen leicht nach unten, sauber heben und betont langsam senken. Kein Schwung.", primary: false },
      { id: "fa6", name: "Rope Pushdown", sub: "Rope Triceps Pushdown (Superset)", focus: "Trizeps", focusColor: "#a78bfa", sets: 3, reps: "10–12", weight: "25–40 kg*", rest: 30, tip: "Am Kabel mit Seil (hohe Rolle): Seil runterdrücken, unten die Enden auseinander, Ellbogen fixiert. Superset — direkt zum Rope Curl.", primary: false },
      { id: "fa8", name: "Rope Curl", sub: "Rope Cable Curl (Superset)", focus: "Bizeps", focusColor: "#a78bfa", sets: 3, reps: "10–12", weight: "20–35 kg*", rest: 90, tip: "Gleiches Seil (tiefe Rolle): Seil nach oben curlen (Hammer-Grip), Ellbogen am Körper. Direkt nach dem Pushdown, danach Pause.", primary: false },
      { id: "fa7", name: "Wadenheben", sub: "Calf Raise", focus: "Waden", focusColor: "#c4b5fd", sets: 3, reps: "15–20", weight: "60–80 kg*", rest: 60, tip: "Volle Bewegung — ganz runter, ganz rauf. Oben 1 Sek halten.", primary: false },
    ],
    notes: [
      "Kürzere Ganzkörper-Session (Variante A) — für Wochen mit wenig Zeit.",
      "Wechsle A und B ab, oder wähle je nach Tagesform. Zusammen decken A + B alles ab.",
      "Compounds zuerst (Bankdrücken, Latzug, Beinpresse), dann der Rest.",
    ],
    stretches: [
      { id: "fas1", name: "Türrahmen-Brustdehnung", sub: "Doorway Pec Stretch", target: "Brust", hold: 30, tip: "Unterarm an den Türrahmen, sanft nach vorne lehnen. Pro Seite." },
      { id: "fas2", name: "Lat-Dehnung", sub: "Overhead Lat Stretch", target: "Latissimus", hold: 30, tip: "An Stange fassen, Hüfte nach hinten, Lat lang machen. Pro Seite." },
      { id: "fas3", name: "Quadrizeps stehend", sub: "Standing Quad Stretch", target: "Quadrizeps", hold: 30, tip: "Fuß zum Po ziehen, Knie zusammen, Hüfte leicht nach vorne. Pro Seite." },
    ],
    warmup: [
      { id: "faw1", name: "Katze-Kuh", sub: "Cat-Cow", target: "Mobilität", reps: "1×10", tip: "Rücken abwechselnd runden und strecken, ruhig atmen." },
      { id: "faw2", name: "Band Pull-Apart", sub: "Band Pull-Apart", target: "Schulter / Rücken", reps: "1×15", tip: "Band vor der Brust auseinanderziehen — wärmt Schultern auf." },
    ],
  },
  fullB: {
    id: "fullB",
    label: "Full Body B",
    icon: "fullbody",
    tag: "Ganzkörper · kurz B",
    duration: "45–60 Min",
    restHours: 48,
    accent: "#d946ef",
    accentDim: "#241026",
    bg: "#140617",
    headerBg: "linear-gradient(135deg, #24102a 0%, #140617 100%)",
    exercises: [
      { id: "fb1", name: "Schrägbank Kurzhantel", sub: "Incline Dumbbell Press", focus: "Obere Brust", focusColor: "#d946ef", sets: 3, reps: "8–10", weight: "16–22 kg", rest: 120, tip: "30–45° Neigung, Kurzhanteln kontrolliert nach oben. Deckt die obere Brust ab.", primary: true },
      { id: "fb2", name: "Rudern", sub: "Seated Cable Row", focus: "Oberer Rücken", focusColor: "#e879f9", sets: 3, reps: "10–12", weight: "45–60 kg*", rest: 90, tip: "Aufrecht sitzen, zum Bauch ziehen, Schulterblätter zusammen. Horizontaler Zug — wichtig für Haltung.", primary: true, posture: true },
      { id: "fb3", name: "Beinbeuger sitzend", sub: "Seated Leg Curl", focus: "Beinbeuger", focusColor: "#e879f9", sets: 3, reps: "12–15", weight: "30–50 kg*", rest: 90, tip: "Aufrecht sitzen, Beine kontrolliert beugen und langsam strecken. Hamstrings.", primary: false },
      { id: "fb4", name: "Abduktor Maschine", sub: "Hip Abductor", focus: "Hüfte / Stabilität", focusColor: "#f0abfc", sets: 3, reps: "15–20", weight: "40–60 kg*", rest: 60, tip: "Beine gegen den Widerstand nach außen. Stabilisiert die Hüfte.", primary: false },
      { id: "fb5", name: "Adduktoren Maschine", sub: "Hip Adductor (Inner Thigh)", focus: "Adduktoren / Innenschenkel", focusColor: "#f0abfc", sets: 3, reps: "15–20", weight: "40–60 kg*", rest: 60, tip: "Beine gegen den Widerstand zusammenführen, kurz halten, langsam öffnen. Innenschenkel.", primary: false },
      { id: "fb6", name: "Face Pulls", sub: "Face Pull", focus: "Hintere Schulter / Haltung", focusColor: "#e879f9", sets: 3, reps: "15–20", weight: "20–35 kg*", rest: 60, tip: "Seil auf Gesichtshöhe, zu den Ohren ziehen, Schulterblätter zusammen. Top gegen Rundschultern.", primary: false, posture: true },
      { id: "fb8", name: "Rope Pushdown", sub: "Rope Triceps Pushdown (Superset)", focus: "Trizeps", focusColor: "#e879f9", sets: 3, reps: "10–12", weight: "25–40 kg*", rest: 30, tip: "Am Kabel mit Seil (hohe Rolle): Seil runterdrücken, unten die Enden auseinander, Ellbogen fixiert. Superset — direkt zum Rope Curl.", primary: false },
      { id: "fb7", name: "Rope Curl", sub: "Rope Cable Curl (Superset)", focus: "Bizeps", focusColor: "#e879f9", sets: 3, reps: "10–12", weight: "20–35 kg*", rest: 90, tip: "Gleiches Seil (tiefe Rolle): Seil nach oben curlen (Hammer-Grip), Ellbogen am Körper. Direkt nach dem Pushdown, danach Pause.", primary: false },
    ],
    notes: [
      "Kürzere Ganzkörper-Session (Variante B) — Gegenstück zu A.",
      "Wechsle A und B ab. B legt mehr Fokus auf Rücken/Haltung, Beinbeuger und Adduktoren.",
      "Compounds zuerst (Schrägbank, Rudern), dann die Isolationen.",
    ],
    stretches: [
      { id: "fbs1", name: "Brustöffner", sub: "Chest Opener", target: "Anti-Rundrücken", hold: 30, tip: "Hände hinter dem Rücken verschränken, Brust öffnen." },
      { id: "fbs2", name: "Beinbeuger-Dehnung", sub: "Hamstring Stretch", target: "Beinbeuger", hold: 30, tip: "Bein gestreckt, Hüfte nach hinten, Rücken gerade. Pro Seite." },
      { id: "fbs3", name: "Figure-4 / Taube", sub: "Piriformis Stretch", target: "Po / Hüfte", hold: 30, tip: "Knöchel über das gegenüberliegende Knie, sanft heranziehen. Pro Seite." },
    ],
    warmup: [
      { id: "fbw1", name: "Band Pull-Apart", sub: "Band Pull-Apart", target: "Schulter / Rücken", reps: "1×15", tip: "Band vor der Brust auseinanderziehen, Schulterblätter zusammen." },
      { id: "fbw2", name: "Glute Bridge", sub: "Glute Bridge", target: "Gesäß", reps: "1×15", tip: "Becken hochdrücken, oben Gesäß anspannen." },
    ],
  },
  push: {
    id: "push",
    label: "Push",
    icon: "dumbbell",
    tag: "Push · Brust/Schulter/Trizeps",
    duration: "60–75 Min",
    accent: "#ef4444",
    accentDim: "#2a0f0f",
    bg: "#160a0a",
    headerBg: "linear-gradient(135deg, #2a0f0f 0%, #160a0a 100%)",
    exercises: [
      { id: "pu1", name: "Bankdrücken", sub: "Bench Press", focus: "Brust", focusColor: "#ef4444", sets: 4, reps: "8", weight: "40–60 kg*", rest: 180, tip: "Schulterblätter zusammen, Füße fest, Stange zur unteren Brust. Letzter Satz bis zum Muskelversagen.", primary: true },
      { id: "pu2", name: "Schrägbank Kurzhantel", sub: "Incline DB Press", focus: "Obere Brust", focusColor: "#f87171", sets: 3, reps: "8", weight: "16–22 kg", rest: 150, tip: "30–45° Neigung, Kurzhanteln kontrolliert nach oben. Letzter Satz bis zum Versagen.", primary: false },
      { id: "pu3", name: "Schulterdrücken Kurzhantel", sub: "Dumbbell Shoulder Press", focus: "Schulter", focusColor: "#ef4444", sets: 3, reps: "10", weight: "12–18 kg", rest: 120, tip: "Aufrecht sitzen, Kurzhanteln über Kopf drücken, nicht ganz durchstrecken.", primary: true },
      { id: "pu4", name: "Kabel-Flys", sub: "Cable Flys", focus: "Brust", focusColor: "#f87171", sets: 3, reps: "12", weight: "10–20 kg*", rest: 90, tip: "Leichte Ellbogenbeugung fixiert, Brust unter Spannung zusammenführen.", primary: false },
      { id: "pu5", name: "Seitheben", sub: "Lateral Raise", focus: "Seitliche Schulter", focusColor: "#f87171", sets: 3, reps: "12", weight: "6–10 kg", rest: 60, tip: "Sauber heben, betont langsam senken, kein Schwung.", primary: false },
      { id: "pu6", name: "Brustpresse Maschine", sub: "Chest Press Machine", focus: "Brust", focusColor: "#f87171", sets: 3, reps: "10", weight: "40–70 kg*", rest: 90, tip: "Sitzend, Griffe auf Brusthöhe, kontrolliert nach vorne drücken, nicht ganz durchstrecken. Gewicht frei wählbar — kein Körpergewicht zu stemmen.", primary: false },
      { id: "pu7", name: "Trizeps Rope Pushdown", sub: "Tricep Rope Pull-down", focus: "Trizeps", focusColor: "#f87171", sets: 3, reps: "12", weight: "25–40 kg*", rest: 60, tip: "Am Kabel mit Seil: runterdrücken, unten Enden auseinander, Ellbogen fixiert.", primary: false },
    ],
    notes: [
      "Push-Tag (Brust, Schultern, Trizeps) aus dem PPL-Split.",
      "2–3 Min Pause zwischen den Sätzen.",
      "Letzter Satz jeder Übung bis zum Muskelversagen.",
    ],
    stretches: [
      { id: "pus1", name: "Türrahmen-Brustdehnung", sub: "Doorway Pec Stretch", target: "Brust", hold: 30, tip: "Unterarm an den Türrahmen, sanft nach vorne lehnen. Pro Seite." },
      { id: "pus2", name: "Trizeps Overhead", sub: "Overhead Triceps", target: "Trizeps", hold: 30, tip: "Ellbogen hinter den Kopf, Hand Richtung gegenüberliegendes Schulterblatt. Pro Seite." },
      { id: "pus3", name: "Cross-Body Schulter", sub: "Cross-Body Shoulder", target: "Hintere Schulter", hold: 30, tip: "Arm vor die Brust ziehen, sanft heranziehen. Pro Seite." },
    ],
  },
  pull: {
    id: "pull",
    label: "Pull",
    icon: "back",
    tag: "Pull · Rücken/Bizeps",
    duration: "55–70 Min",
    accent: "#06b6d4",
    accentDim: "#0a2029",
    bg: "#06131a",
    headerBg: "linear-gradient(135deg, #0a2029 0%, #06131a 100%)",
    exercises: [
      { id: "pl1", name: "Latzug breit", sub: "Lat Pull-down Wide Grip", focus: "Latissimus", focusColor: "#06b6d4", sets: 4, reps: "8", weight: "45–65 kg*", rest: 150, tip: "Weiter Griff, Stange zur oberen Brust, Ellbogen nach unten, Schulterblätter senken. Volle Dehnung oben.", primary: true },
      { id: "pl2", name: "Rudern sitzend breit", sub: "Seated Row Wide Grip", focus: "Oberer Rücken", focusColor: "#22d3ee", sets: 3, reps: "8", weight: "45–60 kg*", rest: 120, tip: "Aufrecht, zum Bauch ziehen, Schulterblätter zusammen. Kein Schwung.", primary: false, posture: true },
      { id: "pl3", name: "Latzug enger Griff", sub: "Close/Neutral-Grip Lat Pulldown", focus: "Latissimus", focusColor: "#22d3ee", sets: 3, reps: "10", weight: "40–60 kg*", rest: 120, tip: "Enger/neutraler V-Griff, zur oberen Brust ziehen, Ellbogen nach unten. Wie ein Klimmzug, aber Gewicht frei wählbar. Volle Dehnung oben, kein Schwung.", primary: false },
      { id: "pl4", name: "Vorgebeugtes KH-Rudern", sub: "Bent Over DB Row", focus: "Rücken", focusColor: "#22d3ee", sets: 3, reps: "12", weight: "18–26 kg", rest: 90, tip: "Beide Kurzhanteln, im Hüfthinge (Rücken gerade, Brust vor), Ellbogen nach hinten ziehen, Schulterblätter zusammen. Kein Schwung.", primary: false, posture: true },
      { id: "pl5", name: "Bizeps Curl Maschine", sub: "Machine Bicep Curl", focus: "Bizeps", focusColor: "#22d3ee", sets: 3, reps: "12", weight: "25–40 kg*", rest: 60, tip: "Volle Dehnung unten, oben anspannen. Kein Schwung, keine halben Reps.", primary: false },
      { id: "pl6", name: "KH Hammer Curls", sub: "DB Hammer Curls", focus: "Bizeps / Unterarm", focusColor: "#22d3ee", sets: 3, reps: "10", weight: "10–16 kg", rest: 60, tip: "Neutraler Griff (Hammer), Ellbogen am Körper, sauber curlen.", primary: false },
    ],
    notes: [
      "Pull-Tag (Rücken, Bizeps) aus dem PPL-Split.",
      "Volle Dehnung unten bei jeder Wiederholung.",
      "Kein Schwung, keine halben Wiederholungen.",
    ],
    stretches: [
      { id: "pls1", name: "Lat-Dehnung", sub: "Overhead Lat Stretch", target: "Latissimus", hold: 30, tip: "An Stange fassen, Hüfte nach hinten, Lat lang machen. Pro Seite." },
      { id: "pls2", name: "Bizeps-Dehnung an der Wand", sub: "Biceps Wall Stretch", target: "Bizeps", hold: 30, tip: "Arm gestreckt an die Wand, Körper langsam wegdrehen. Pro Seite." },
      { id: "pls3", name: "Kindhaltung", sub: "Child's Pose", target: "Unterer Rücken", hold: 45, tip: "Fersensitz, Arme lang nach vorne, tief atmen." },
    ],
  },
  legs: {
    id: "legs",
    label: "Legs",
    icon: "legs",
    tag: "Legs · Beine",
    duration: "60–75 Min",
    accent: "#84cc16",
    accentDim: "#182100",
    bg: "#0e1405",
    headerBg: "linear-gradient(135deg, #1a2400 0%, #0e1405 100%)",
    exercises: [
      { id: "lg1", name: "Kniebeuge", sub: "Back Squat", focus: "Quadrizeps / Po", focusColor: "#84cc16", sets: 4, reps: "8", weight: "40–60 kg*", rest: 180, tip: "Stange am oberen Rücken, tief und kontrolliert. 2–3 Sek runter bei jeder Wiederholung. 3 Min Pause.", primary: true },
      { id: "lg2", name: "Beinpresse", sub: "Leg Press", focus: "Quadrizeps / Po", focusColor: "#a3e635", sets: 3, reps: "15", weight: "80–120 kg*", rest: 120, tip: "Füße schulterbreit, mittig. Knie nicht ganz durchstrecken.", primary: true },
      { id: "lg3", name: "Beinbeuger sitzend", sub: "Seated Hamstring Curl", focus: "Beinbeuger", focusColor: "#a3e635", sets: 3, reps: "12", weight: "30–50 kg*", rest: 90, tip: "Aufrecht sitzen, Beine kontrolliert beugen und langsam strecken.", primary: false },
      { id: "lg4", name: "Beinstrecker", sub: "Seated Leg Extension", focus: "Quadrizeps", focusColor: "#a3e635", sets: 3, reps: "12", weight: "40–60 kg*", rest: 90, tip: "Oben kurz halten, langsam runter.", primary: false },
      { id: "lg5", name: "Goblet Squats", sub: "Goblet Squats", focus: "Beine / Po", focusColor: "#a3e635", sets: 3, reps: "15", weight: "16–24 kg", rest: 90, tip: "Kurzhantel/Kettlebell vor der Brust, aufrechter Oberkörper, tief gehen.", primary: false },
      { id: "lg6", name: "Wadenheben sitzend", sub: "Seated Calf Raise", focus: "Waden", focusColor: "#a3e635", sets: 3, reps: "15", weight: "40–60 kg*", rest: 60, tip: "Volle Bewegung — ganz runter, ganz rauf. Oben 1 Sek halten.", primary: false },
    ],
    notes: [
      "Legs-Tag aus dem PPL-Split (mit Kniebeugen — anders als der rückenschonende 'Beine'-Tag).",
      "3 Min Pause bei den Kniebeugen.",
      "2–3 Sek exzentrisch (runter) bei jeder Wiederholung.",
    ],
    stretches: [
      { id: "lgs1", name: "Quadrizeps stehend", sub: "Standing Quad Stretch", target: "Quadrizeps", hold: 30, tip: "Fuß zum Po ziehen, Knie zusammen, Hüfte leicht nach vorne. Pro Seite." },
      { id: "lgs2", name: "Beinbeuger-Dehnung", sub: "Hamstring Stretch", target: "Beinbeuger", hold: 30, tip: "Bein gestreckt, Hüfte nach hinten, Rücken gerade. Pro Seite." },
      { id: "lgs3", name: "Wadendehnung an der Wand", sub: "Wall Calf Stretch", target: "Waden", hold: 30, tip: "Ferse am Boden, hinteres Bein gestreckt, gegen die Wand lehnen. Pro Seite." },
    ],
  },
};

// Standalone hip & glute mobility routine — for tight/inactive glutes and
// shortened hip flexors from prolonged sitting. Do anytime, incl. rest days.
export const MOBILITY = {
  label: "Hüfte & Glutes",
  accent: "#ec4899",
  intro: "Gegen verkürzte Hüftbeuger und tight/inaktive Glutes durch langes Sitzen. Täglich oder an Rest-Tagen machbar.",
  sections: [
    {
      title: "Aktivierung",
      kind: "reps",
      items: [
        { id: "m_act1", name: "Glute Bridge", sub: "Glute Bridge", target: "Gesäß", reps: "2×15", tip: "Auf dem Rücken, Fersen nah am Po. Becken hochdrücken, oben Gesäß 1 Sek fest anspannen." },
        { id: "m_act2", name: "Clamshells", sub: "Clamshell", target: "Gesäß (seitlich)", reps: "2×15/Seite", tip: "Seitlage, Knie gebeugt. Oberes Knie öffnen, ohne das Becken nach hinten zu drehen." },
        { id: "m_act3", name: "Monster Walks", sub: "Banded Lateral Walk", target: "Abduktoren / Gesäß", reps: "2×10 Schritte", tip: "Band um die Knie, leichte Hocke, seitlich gehen, Bandspannung halten." },
        { id: "m_act4", name: "Hip Thrust am Boden", sub: "Floor Hip Thrust", target: "Gesäß", reps: "2×12", tip: "Oberer Rücken erhöht oder am Boden, Becken kraftvoll nach oben, oben anspannen." },
        { id: "m_act5", name: "Bird-Dog", sub: "Bird Dog", target: "Rumpf / Gesäß", reps: "2×8/Seite", tip: "Vierfüßlerstand, gegenüberliegenden Arm und Bein strecken, Rumpf stabil." },
      ],
    },
    {
      title: "Mobilität & Dehnen",
      kind: "hold",
      items: [
        { id: "m_str1", name: "Figure-4 / Taube", sub: "Piriformis / Pigeon", target: "Piriformis / Gesäß", hold: 45, tip: "Knöchel über das gegenüberliegende Knie ziehen, oder Pigeon am Boden. Pro Seite." },
        { id: "m_str2", name: "Hüftbeuger-Ausfallschritt", sub: "Hip Flexor Lunge", target: "Hüftbeuger", hold: 45, tip: "Tiefer Ausfallschritt, Becken nach vorne schieben, aufrecht bleiben. Pro Seite." },
        { id: "m_str3", name: "90/90 Hüftrotation", sub: "90/90 Hip Switch", target: "Hüftrotatoren", hold: 45, tip: "Beide Knie 90°, ein Bein vorn, ein Bein seitlich. Aufrecht sitzen, sanft nach vorne lehnen. Pro Seite." },
        { id: "m_str4", name: "Adduktoren-Dehnung", sub: "Adductor Stretch", target: "Innenschenkel", hold: 30, tip: "Breiter Stand oder Frosch-Position, Gewicht sanft zur Seite / nach hinten." },
        { id: "m_str5", name: "Kindhaltung mit Rotation", sub: "Thread the Needle", target: "Gesäß / unterer Rücken", hold: 45, tip: "Aus der Kindhaltung einen Arm unter dem Körper durchführen. Pro Seite." },
        { id: "m_str6", name: "Liegende Wirbelsäulendrehung", sub: "Supine Spinal Twist", target: "Gesäß / Hüfte", hold: 45, tip: "Rückenlage, ein Knie über den Körper zur anderen Seite fallen lassen. Pro Seite." },
      ],
    },
  ],
};
